config/routes.rb
Links::Application.routes.draw do
	resources :users
	resources :links do
		resources :comments, :only => [:destroy]
	end
	resource :session
	resources :comments, :except => [:destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :link_id
  validates :body, :presence => true

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :user_id, :title, :url
  validates :title, :presence => true
  validates :url, :presence => { :message => "Url can't be blank"}

  has_many(
  	:comments,
  	:class_name => "Comment",
  	:foreign_key => :link_id,
  	:primary_key => :id
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :session_token
  validates :password, :username, :presence => true
  validates :password, :length => { :minimum => 6 }

  def reset_token
  	self.session_token = SecureRandom::urlsafe_base64(16)
  	self.save!
  	self.session_token
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
	end

	def create
		@comment = Comment.new(params[:comment])
		if @comment.save
			redirect_to link_url(@comment[:link_id])
		else
			flash[:errors] = @comment.errors.full_messages
			redirect_to link_url(@comment[:link_id])
		end

	end

	def destroy
		@comment = Comment.find(params[:link_id])
		@comment.destroy
		redirect_to link_url(params[:id])

	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def index
		redirect_to new_session_url unless logged_in?
		@users = User.all
		@links = Link.all
	end

	def new
		redirect_to new_session_url unless logged_in?
	end

	def create
		@link = Link.new(params[:link])
		if @link.save
			#session[:session_token] = @user.reset_token
			#fail
			redirect_to link_url(@link)
		else
			flash[:errors] = @link.errors.full_messages
			redirect_to new_link_url
		end
	end

	def show
		@link = Link.find(params[:id])
	end

	def edit
		@link = Link.find(params[:id])
	end

	def update
		@link = Link.find(params[:id])
		@link.update_attributes(params[:link])
		if @link.save
			redirect_to link_url(@link)
		else
			flash[:errors] = @link.errors.full_messages
			redirect_to link_url(@link)
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by_username_and_password(
			params[:user][:username],
			params[:user][:password]
		)
		if @user
			session[:session_token] = @user.reset_token
			redirect_to links_url
		else
			flash[:errors] = ["Invalid Username or Password"]
			redirect_to new_session_url
		end

	end

	def destroy
		session[:session_token] = nil
		self.current_user = nil
		redirect_to new_session_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			session[:session_token] = @user.reset_token
			#fail
			redirect_to links_url
		else
			flash[:errors] = @user.errors.full_messages
			redirect_to new_user_url
		end
	end


	#links index

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	attr_writer :current_user

	def current_user
		return nil unless session[:session_token]
		@current_user ||= User.find_by_session_token(session[:session_token])
		@current_user
	end

	def logged_in?
		!!self.current_user
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
			<%= error %>
		<% end %>
	<% end %>

	

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
Edit Link
<% if logged_in? %>
	<%= button_to "Sign Out", session_url, :method => :delete %>
	<%= link_to "New Link", new_link_url, :method => :get %>
<% else %>
	<%= button_to "Sign In", new_session_url, :method => :get %>
<% end %>

<form action="<%= link_url(@link) %>" method="post">
	Title
	<input type="text" id="Title" name="link[title]" value="<%= @link.title %>">
	URL
	<input type="text" id="URL" name="link[url]" value="<%= @link.url %>">

	<input type="hidden" name="form_authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="_method" value="PUT">
	<input type="submit" value="Update Link">
</form>

app/views/links/index.html.erb
<% if logged_in? %>
	<%= button_to "Sign Out", session_url, :method => :delete %>
	<%= link_to "New Link", new_link_url, :method => :get %>
<% else %>
	<%= button_to "Sign In", new_session_url, :method => :get %>
<% end %>

<% @users.each do |user| %>
	<%= user.username %>
<% end %>

<% @links.each do |link| %>
	<%= "#{link.title} #{link.url}" %>
	<%= link_to "#{link.title}", link_url(link) %>
	<%= link.url %>
<% end %>

app/views/links/new.html.erb
New Link

<% if logged_in? %>
	<%= button_to "Sign Out", session_url, :method => :delete %>
	<%= link_to "New Link", new_link_url, :method => :get %>
<% else %>
	<%= button_to "Sign In", new_session_url, :method => :get %>
<% end %>

<form action="<%= links_url %>" method="post">
	Title
	<input type="text" id="Title" name="link[title]">
	URL
	<input type="text" id="URL" name="link[url]">

	<input type="hidden" name="form_authenticity_token" value="<%= form_authenticity_token %>">
	<input type="submit" value="Create New Link">
</form>

app/views/links/show.html.erb
<% if logged_in? %>
	<%= button_to "Sign Out", session_url, :method => :delete %>
	<%= link_to "New Link", new_link_url, :method => :get %>
	<%= self.current_user.username %>
<% else %>
	<%= button_to "Sign In", new_session_url, :method => :get %>
<% end %>

<%= link_to "Links", links_url, :method => :get %>
<%= @link.title %>
<%= @link.url %>
<%= link_to "Edit Link", edit_link_url(@link), :method => :get %>

<% @link.comments.each do |comment| %>
	<%= comment.body %>
	<form action="<%= link_comment_url(comment.id)%>" method="post">
		<input type="hidden" name="form_authenticity_token" value="<%= form_authenticity_token %>">
		<input type="hidden" name="_method" value="DELETE">
		<input type="submit" value="Remove Comment">
	</form>
<% end %>

Add Comment
<form action="/comments" method="post">
	<input type="text" name="comment[body]" id="Comment">
	<input type="hidden" name="form_authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="comment[link_id]" value="<%= @link.id %>">
	<input type="submit" value="Add Comment">
</form>

app/views/users/new.html.erb
Sign Up
<form action="<%= users_url %>" method="post">

	Username
	<input type="text" id="Username" name="user[username]" value="">
	Password
	<input type="password" id="Password" name="user[password]" value="">

	<input type="hidden" name="form_authenticity_token" value="<%= form_authenticity_token %>">
	<input type="submit" value="Sign Up">

</form>